{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggally
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GGally_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GGally/GGally_{{ version }}.tar.gz
  sha256: 3ad00c8cd6738887b6cbe3450e8418ea1ba7dfd8985bc0e7f59b6f1fe0bf75be

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2 >=3.3.0
    - r-gtable >=0.2.0
    - r-lifecycle
    - r-plyr >=1.8.3
    - r-progress
    - r-reshape >=0.8.5
    - r-rlang
    - r-scales >=1.1.0
  run:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2 >=3.3.0
    - r-gtable >=0.2.0
    - r-lifecycle
    - r-plyr >=1.8.3
    - r-progress
    - r-reshape >=0.8.5
    - r-rlang
    - r-scales >=1.1.0

test:
  commands:
    - $R -e "library('GGally')"           # [not win]
    - "\"%R%\" -e \"library('GGally')\""  # [win]

about:
  home: https://ggobi.github.io/ggally, https://github.com/ggobi/ggally
  license: GPL-2.0-or-later
  summary: " The R package 'ggplot2' is a plotting system based on the grammar of graphics. 'GGally' extends 'ggplot2' by adding several functions to reduce the complexity of combining geometric objects with transformed data. Some of these functions include a pairwise plot matrix, a two group pairwise plot matrix, a parallel\
    \ coordinates plot, a survival plot, and several functions to plot networks."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: GGally
# Version: 2.0.0
# License: GPL (>= 2.0)
# Title: Extension to 'ggplot2'
# Type: Package
# LazyLoad: yes
# LazyData: true
# URL: https://ggobi.github.io/ggally, https://github.com/ggobi/ggally
# BugReports: https://github.com/ggobi/ggally/issues
# Authors@R: c( person("Barret", "Schloerke", role = c("aut", "cre"), email = "schloerke@gmail.com"), person("Di", "Cook", role = c("aut", "ths"), email = "dicook@monash.edu"), person("Joseph", "Larmarange", role = "aut", email = "joseph@larmarange.net"), person("Francois", "Briatte", role = "aut", email = "f.briatte@gmail.com"), person("Moritz", "Marbach", role = "aut", email = "mmarbach@mail.uni-mannheim.de"), person("Edwin", "Thoen", role = "aut", email = "edwinthoen@gmail.com"), person("Amos", "Elberg", role = "aut", email = "amos.elberg@gmail.com"), person("Ott", "Toomet", role = "ctb", email = "otoomet@gmail.com"), person("Jason", "Crowley", role = "aut", email = "crowley.jason.s@gmail.com"), person("Heike", "Hofmann", role = "ths", email = "hofmann@iastate.edu"), person("Hadley", "Wickham", role = "ths", email = "h.wickham@gmail.com") )
# Description: The R package 'ggplot2' is a plotting system based on the grammar of graphics. 'GGally' extends 'ggplot2' by adding several functions to reduce the complexity of combining geometric objects with transformed data. Some of these functions include a pairwise plot matrix, a two group pairwise plot matrix, a parallel coordinates plot, a survival plot, and several functions to plot networks.
# Depends: R (>= 3.1), ggplot2 (>= 3.3.0)
# Imports: grDevices, grid, gtable (>= 0.2.0), plyr (>= 1.8.3), progress, RColorBrewer, reshape (>= 0.8.5), scales (>= 1.1.0), utils, rlang, lifecycle
# Suggests: broom (>= 0.4.0), chemometrics, geosphere (>= 1.5-1), ggforce, Hmisc, igraph (>= 1.0.1), intergraph (>= 2.0-2), maps (>= 3.1.0), mapproj, network (>= 1.12.0), scagnostics, sna (>= 2.3-2), survival, rmarkdown, roxygen2, testthat, crosstalk, knitr, spelling
# RoxygenNote: 7.1.0
# SystemRequirements: openssl
# Encoding: UTF-8
# Language: en-US
# RdMacros: lifecycle
# NeedsCompilation: no
# Packaged: 2020-06-05 18:41:02 UTC; barret
# Author: Barret Schloerke [aut, cre], Di Cook [aut, ths], Joseph Larmarange [aut], Francois Briatte [aut], Moritz Marbach [aut], Edwin Thoen [aut], Amos Elberg [aut], Ott Toomet [ctb], Jason Crowley [aut], Heike Hofmann [ths], Hadley Wickham [ths]
# Maintainer: Barret Schloerke <schloerke@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-06-06 05:00:13 UTC
