{% set version = "2.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggally
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GGally_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GGally/GGally_{{ version }}.tar.gz
  sha256: dce20b47d639aa1ad63d9f14aae48c554d1e787758876c9842bf0e093bab80dd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.4.4
    - r-ggstats
    - r-gtable >=0.2.0
    - r-lifecycle
    - r-magrittr
    - r-plyr >=1.8.3
    - r-progress
    - r-rcolorbrewer
    - r-rlang
    - r-scales >=1.1.0
    - r-tidyr >=1.3.0
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.4.4
    - r-ggstats
    - r-gtable >=0.2.0
    - r-lifecycle
    - r-magrittr
    - r-plyr >=1.8.3
    - r-progress
    - r-rcolorbrewer
    - r-rlang
    - r-scales >=1.1.0
    - r-tidyr >=1.3.0

test:
  commands:
    - $R -e "library('GGally')"           # [not win]
    - "\"%R%\" -e \"library('GGally')\""  # [win]

about:
  home: https://ggobi.github.io/ggally
  dev_url: https://github.com/ggobi/ggally
  license: GPL-2.0-or-later
  summary: " The R package 'ggplot2' is a plotting system based on the grammar of graphics. 'GGally' extends 'ggplot2' by adding several functions to reduce the complexity of combining geometric objects with transformed data. Some of these functions include a pairwise plot matrix, a two group pairwise plot matrix, a parallel
    coordinates plot, a survival plot, and several functions to plot networks."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
