{% set version = "2.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggally
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GGally_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GGally/GGally_{{ version }}.tar.gz
  sha256: fe5eabe9eec66fd578ce244e291d0453846dd2181b39ca9039c157971ba16d09

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-s7 >=0.2.0
    - r-dplyr >=1.1.0
    - r-ggplot2 >=3.5.2
    - r-ggstats >=0.9.0
    - r-gtable >=0.2.0
    - r-lifecycle
    - r-magrittr
    - r-progress
    - r-rlang
    - r-scales >=1.3.0
    - r-tidyr >=1.3.0
  run:
    - r-base
    - r-rcolorbrewer
    - r-s7 >=0.2.0
    - r-dplyr >=1.1.0
    - r-ggplot2 >=3.5.2
    - r-ggstats >=0.9.0
    - r-gtable >=0.2.0
    - r-lifecycle
    - r-magrittr
    - r-progress
    - r-rlang
    - r-scales >=1.3.0
    - r-tidyr >=1.3.0

test:
  commands:
    - $R -e "library('GGally')"           # [not win]
    - "\"%R%\" -e \"library('GGally')\""  # [win]

about:
  home: https://ggobi.github.io/ggally
  dev_url: https://github.com/ggobi/ggally
  license: GPL-2.0-or-later
  summary: " The R package 'ggplot2' is a plotting system based on the grammar of graphics. 'GGally' extends 'ggplot2' by adding several functions to reduce the complexity of combining geometric objects with transformed data. Some of these functions include a pairwise plot matrix, a two group pairwise plot matrix, a parallel
    coordinates plot, a survival plot, and several functions to plot networks."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
