appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: E5nuNR7j8Po6/I1gAgKRODpnUtpj57f+ZavcN5SnslrCvzQ7l/ocTxvOYJLdP8eSXkOVhw/GduXZshoRTlfkae4uUetAUVPmtJ6xuaMI60iErxVoda1wl4HdXR6KOHY+0TgmUaPtHi1ouBm+1VEy/NDJAR+sP7kdMBTl3GIj2/LhO+1P7/SxsAEHSXgBQI7fzyRYRMgqX9AfzH05EFt4yFfcPngsMhYy5WhmtaRhLFRcJCKGNO67Lw7I2JTSeVDqTNE5iV/Yt8iZfNjHGyTpA86U1eOQ+tgRjoym/sl+RPQ/T8Hj0ifGq264EemC/RVZfp0zP6a8pGv2nXWy8X8j+4hOZF5JUCmDUJhgO7suwNzRfPc5kWWWyrCSAD1DElUwDwqwdG8JSjdLRbNut0pM0rBLwzumpy3/jpj1aEMGleWV92BoEnR9fltaWg9I0aZykTej8CNnLhPHAZGqibEB0E1yhSHikUuKTglVGQkHurzKgVGOxzr3IiNMWoSfDK05x7LfCNA1zscwIiT3zqTsS29x3Rs0TnDt8Qydsp6IRZ7l18oWHcCXxJPPEkwAxBi13bufeW88ME5fqFTVVVh6cLz+zLoi6h5bPBVW9hi8k1HsIip7gJW1XPtvRVy5/4UgFTi3y5vkPUiyflTDbsatd6kOdABOXZXg29aLwvEBf4s=}
